;; original name rocket_ext.a
;;

(define (problem pb1)
  (:domain logistics)
  (:requirements :strips) 
  (:objects mxf avrim alex jason pencil paper april michelle betty lisa airplane1 airplane2 bos par lon jfk)
  (:init 
   (cargo mxf)
   (cargo avrim)
	 (cargo alex)
	 (cargo jason)
	 (cargo pencil)
	 (cargo paper)
	 (cargo april)
	 (cargo michelle)
	 (cargo betty)
	 (cargo lisa)
	 (airplane airplane1)
	 (airplane airplane2)
	 (airport lon)
	 (airport par)
	 (airport jfk)
	 (airport bos)
   (at airplane1 jfk)
	 (at airplane2 bos)
	 (at mxf par)
	 (at avrim par)
	 (at alex par)
	 (at jason jfk)
	 (at pencil lon)
	 (at paper lon)
	 (at michelle lon)
	 (at april lon)
	 (at betty lon)
	 (at lisa lon)
	 )
  (:goal (and 
	  (at mxf bos)
	  (at avrim jfk)
	  (at pencil bos)
	  (at alex jfk)
	  (at april bos)
	  (at lisa par)
	  (at michelle jfk)
	  (at jason bos)
	  (at paper par)
	  (at betty jfk)
	  )
	 )
  )
